Probality: # Spawn Probability : Max 100. To add an ore or block, add a line with the block ID.
  cobblestone: 90
  coal_ore: 75
  iron_ore: 50
  redstone_ore: 25
  diamond_ore: 10
  emerald_ore: 2
  gold_ore: 13
  lapis_ore: 10